### PR TITLE
Merge upstream changes into managed process branch

### PR DESCRIPTION
**Pull request by CharityKathure**
**- What I did**
Merge the upstream changes into managed process branch and resolve merge conflicts.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by CharityKathure** [comment]
cc @olljanat

**Comment by olljanat** [comment]
@CharityKathure not front of computer at the moment but I see GitHub saying "This branch cannot be rebased due to conflicts" on "Merge and rebase" option.

"Create a merge commit" is possible but not sure if that is good idea.

**Comment by CharityKathure** [comment]
@olljanat I can't see that message on my side, it shows "there are no conflicts with the base branch".

**Comment by olljanat** [comment]
Looks to be just limitation on GitHub UI side on these git pull requests. I merged it now from command line.

**Pull request merged**
